### ISSUE TITLE
ui: 'packages from x repo' listing walks 'off screen'

### ISSUE THREAD

**Issue by gavanderhoorn** [rosindex/rosindex.github.io#123]
For repositories with many packages, the package list showing all the packages does not wrap anymore. As far as I can remember, it used to do this. See [common_msgs](http://rosindex.github.io/p/actionlib_msgs/github-ros-common_msgs/) for instance.

**Comment by jbohren** [comment]
Can you post a screenshot and the version of the browser you're using?

**Comment by gavanderhoorn** [comment]
Firefox 35.0.1, Ubuntu Precise.

![ros_index_wrapping_issue](https://cloud.githubusercontent.com/assets/4550046/6156531/500efaf0-b23b-11e4-9ea8-b7ccd844d5bd.png)

**Comment by jbohren** [comment]
This should be fixed, I also made the page a little wider, so look here for an example that should wrap:

http://rosindex.github.io/p/jsk_data/github-jsk-ros-pkg-jsk_common/#hydro

**Comment by gavanderhoorn** [comment]
Yes, I was just looking at all the new toys and improvements, and noticed that this is now fixed.

Thanks, getting awesomer (if that is a word) by the minute!
