### ISSUE TITLE
add instructions for contributing to rosdistro files

### ISSUE THREAD

**Issue by jbohren** [rosindex/rosindex.github.io#16]

**Comment by jbohren** [comment]
The current instructions are here: http://wiki.ros.org/rosdistro/Tutorials/Indexing%20Your%20ROS%20Repository%20for%20Documentation%20Generation

They could be greatly improved.

**Comment by jbohren** [comment]
@davetcoleman http://rosindex.github.io/contribute/add_repo/

**Comment by davetcoleman** [comment]
Wow, impressive documentation!
