### ISSUE TITLE
Clicking on repo URL should open hyperlink

### ISSUE THREAD

**Issue by davetcoleman** [rosindex/rosindex.github.io#62]
![screen shot 2015-01-19 at 11 44 08 am](https://cloud.githubusercontent.com/assets/561060/5805884/9ba613ea-9fd0-11e4-97af-b7a10dea990d.png)

Doesn't work when i click there

**Comment by jbohren** [comment]
This is actually the list of alternative instances if someone wants their fork indexed. I think that's the one sort of "advanced" feature of the site. I think it should be disabled if there aren't any known alternatives. I'll make this clearer #72
