### ISSUE TITLE
Change ROS Index to use ROS Logo

### ISSUE THREAD

**Issue by davetcoleman** [rosindex/rosindex.github.io#64]
It would be more convincing as an official tool of ROS to use the 9 dots icon

**Comment by jbohren** [comment]
I'll put this as an enhancement, we'll see what the osrf guys think of this when I announce it.

**Comment by jbohren** [comment]
What do you think of this? http://rosindex.github.io/assets/rosindex_logo.png

**Comment by davetcoleman** [comment]
ooooh nice! me like

**Comment by jbohren** [comment]
> Tank: So what do you need? Besides a miracle.
> Neo: Packages. Lots of packages.

**Comment by gavanderhoorn** [comment]
:). +1 on the logo.

**Comment by jbohren** [comment]
> Is that a perspective projection?

Either that or the distant dots are just physically smaller ;)

Closing this with the new logo on the site: http://rosindex.github.io/about/
