### ISSUE TITLE
Pre-load Index

### ISSUE THREAD

**Issue by davetcoleman** [rosindex/rosindex.github.io#76]
When searching for the first time I experienced ~10-15s waiting with the message "Loading Index..." - could this be loaded as soon as the page finishes loading rather then once i type my query?

**Comment by jbohren** [comment]
Yeah, pre-loading the json files could probably be done.

**Comment by jbohren** [comment]
I gave this a shot over the weekend and based on my experience, it tends to just slow down all the other pages while the browser grabs it from the cache, especially on mobile. Unless there's a better way to handle this, I'm going to say that there will jut have to be an initial delay on the search page after the index has been updated. 

There are some other tweaks that might just make the default search return the same results, but with fewer rows. That would greatly reduce the size of the json indexes and increase the speed at which they can be loaded.

See here for more discussion: https://github.com/rosindex/rosindex.github.io/issues/110#issuecomment-72499038
