### ISSUE TITLE
Wiki links should jump to specific package version

### ISSUE THREAD

**Issue by shaun-edwards** [rosindex/rosindex.github.io#89]
The wiki link (ex: [here](http://rosindex.github.io/p/motoman_driver/github-ros-industrial-motoman/#hydro)) should link to hydro specifc wiki page.  Of course, as I writing this, I can't seem to find the hyperlink trick that makes this possible.  Perhaps this isn't possible anymore.

**Comment by jbohren** [comment]
Yeah, this would be nice, unfortunately the distro versioning on the wiki isn't well standardized. At least the wiki buttons for `motoman_driver` work. The same can't be said for other pages: https://www.youtube.com/watch?v=mBY6GYjQULI

**Comment by jbohren** [comment]
(: maybe this should be a ticket on https://github.com/ros-infrastructure/roswiki

**Comment by jbohren** [comment]
Ah it's `wiki.ros.org/something?distro=DISTRO`

**Comment by jbohren** [comment]
Done: http://rosindex.github.io/p/fanuc/github-ros-industrial-fanuc/#hydro
