### ISSUE TITLE
Discovery of 'readme' files seems case sensitive?

### ISSUE THREAD

**Issue by gavanderhoorn** [rosindex/rosindex.github.io#95]
According to [rosindex/r/fanuc](http://rosindex.github.io/r/fanuc/), the repository does not contain a README. Technically true: the file is called `readme.md`, not `README.md`.

Is this intentional? I hope lowercase readmes are allowed as well :) ?

**Comment by jbohren** [comment]
Yeah, these should be picked up.

**Comment by jbohren** [comment]
resolved in ce3fdae3d54b2b4a2a8419ddf1713092deed0dd2
