### ISSUE TITLE
No indication of package deprecation

### ISSUE THREAD

**Issue by gavanderhoorn** [rosindex/rosindex.github.io#96]
Browsing [rosindex/p/fanuc_assets](http://rosindex.github.io/p/fanuc_assets/github-ros-industrial-fanuc/) I noticed that the UI does not have an indicator for package deprecation.

That particular package has a `deprecated` element in the `export` section of its [manifest](https://github.com/ros-industrial/fanuc/blob/c4f3117aa677642b300fe55a01339cc7c0ad423b/fanuc_assets/package.xml#L30), perhaps the UI should provide a visual indication of that as well?

**Comment by jbohren** [comment]
Yeah, this should definitely be displayed.

**Comment by jbohren** [comment]
better? http://rosindex.github.io/p/fanuc_assets/github-ros-industrial-fanuc/#indigo

**Comment by vooon** [comment]
But now i see "deprecated" banner on mavros and ntpd_driver...

**Comment by jbohren** [comment]
> But now i see "deprecated" banner on mavros and ntpd_driver...

Brief hiccup.

**Comment by gavanderhoorn** [comment]
@jbohren wrote:
> better? http://rosindex.github.io/p/fanuc_assets/github-ros-industrial-fanuc/#indigo

Well .. that certainly can't be missed :).

But I guess we can never be too clear about deprecation, so great.

**Comment by gavanderhoorn** [comment]
@jbohren: after looking up some more deprecated packages, I must say I like the in-your-face deprecation warning. It's immediately clear to users that a package is deprecated, and, if the pkg manifest is properly setup, which package to use as a replacement is in the displayed message.

**Comment by vooon** [comment]
@jbohren A day ago i seen orange deprecation warning box, but now it's gone.

**Comment by jbohren** [comment]
> Would it perhaps be an idea to also add the deprecation to the Package Summary - Status block on the left?

Yeah, especially to clear up the distinction between a `developed` repository which may contain `deprecated` packages. I'm going to rename the `Status` panel `Repository Summary` and move the package-specific information over to the `Details` panel.

**Comment by jbohren** [comment]
@gavanderhoorn Feel free to close this when you're satisfied with the current presentation, but I think it should be good now.

**Comment by gavanderhoorn** [comment]
I'm happy with this.

Thanks
